FROM apache/airflow:2.7.1

USER root

# Create directories with correct permissions
RUN mkdir -p \
    /opt/airflow/logs \
    /opt/airflow/dags \
    /opt/airflow/plugins \
    /opt/airflow/data && \
    chown -R airflow:root /opt/airflow && \
    chmod -R 775 /opt/airflow

USER airflow