#tests
GRAPH.QUERY expert_graph "MATCH (e1:Expert)-[s:SIMILAR_TO]->(e2:Expert) WHERE e1.orcid IN ['https://orcid.org/0000-0003-2462-9471', 'https://orcid.org/0000-0001-6266-3342'] RETURN e1.orcid AS orcid, e2.orcid AS similar_orcid, e2.name AS name, s.score AS similarity_score ORDER BY s.score DESC LIMIT 10"

GRAPH.QUERY expert_graph "MATCH (e1:Expert)-[s:SIMILAR_TO]->(e2:Expert) WHERE e1.orcid = 'https://orcid.org/0000-0001-6266-3342' RETURN e1.orcid AS orcid, e2.orcid AS similar_orcid, e2.name AS name, s.score AS similarity_score ORDER BY s.score DESC LIMIT 10"
https://orcid.org/0000-0001-6266-3342

 """
        MATCH (e1:Expert)-[s:SIMILAR_TO]->(e2:Expert)
        WHERE e1.orcid = $orcid
        RETURN e1.orcid AS orcid, e2.orcid AS similar_orcid, e2.name AS name, s.score AS similarity_score
        ORDER BY s.score DESC
        LIMIT $limit
        """